name: Build client

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: '1.20'
        executable_compression: upx -v
        compress_assets: 'OFF'
